"""Recipe → canonical → rules. Shared by the ``run_pipeline`` tool and the spine's build node.

A standard recipe is generated by our own code and runs in-process after the
static check. Anything a model authored runs only in the sandbox.
"""

from __future__ import annotations

import hashlib
import json
import shlex
from pathlib import Path
from typing import Any

from langchain_core.tools import BaseTool, tool
from onboarding_sdk import recipes
from onboarding_sdk.canonical import AffiliateCanonical
from onboarding_sdk.entities.affiliate import AffiliateResult, process

from ..observability import span
from ..run_context import RunContext
from ..sandbox.base import IN_DIR, WORK_DIR
from ._common import fail, ok


class RecipeFailed(RuntimeError):
    pass


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sandbox_python(args: str) -> str:
    """A python command that cannot import modules planted in /work (-P, cwd outside /work)."""
    return f"cd / && python -P -m {args}"


def execute_recipe(ctx: RunContext, recipe: dict[str, Any]) -> AffiliateCanonical:
    path = Path(recipe["path"])
    if not path.is_file() or recipe.get("sha256") != sha256_of(path):
        raise RecipeFailed("the recipe file does not match its recorded hash; it changed after it was checked")
    if recipe["origin"] == "standard":
        try:
            return recipes.run(path, ctx.upload_path)
        except ValueError as exc:
            raise RecipeFailed(str(exc)) from exc
    with span("sandbox.recipe_run", run_id=ctx.run_id):
        try:
            return _run_in_sandbox(ctx, path)
        except RecipeFailed:
            raise
        except Exception as exc:  # a sandbox that cannot start or answer is a failed run, not a crash
            raise RecipeFailed(f"sandbox error: {type(exc).__name__}: {exc}") from exc


def _run_in_sandbox(ctx: RunContext, path: Path) -> AffiliateCanonical:
    box = ctx.sandbox()
    uploaded = box.upload_files([(f"{WORK_DIR}/recipe.py", path.read_bytes())])
    if uploaded[0].error:
        raise RecipeFailed(f"could not place the recipe in the sandbox: {uploaded[0].error}")
    upload = shlex.quote(f"{IN_DIR}/{ctx.upload_path.name}")
    result = box.execute(sandbox_python(f"onboarding_sdk.recipes run {WORK_DIR}/recipe.py {upload}"), timeout=300)
    try:
        payload = json.loads(result.output.strip().splitlines()[-1])
    except (IndexError, json.JSONDecodeError) as exc:
        raise RecipeFailed(f"recipe produced no result: {result.output[-500:]}") from exc
    if result.exit_code != 0 or not payload.get("ok"):
        raise RecipeFailed(payload.get("error") or result.output[-500:])
    return AffiliateCanonical.from_dict(payload["canonical"])


def result_key(ctx: RunContext, recipe: dict[str, Any]) -> str:
    return f"{recipe.get('sha256')}:{json.dumps(ctx.options.to_dict(), sort_keys=True)}"


def build(ctx: RunContext, recipe: dict[str, Any]) -> AffiliateResult:
    ctx.canonical = execute_recipe(ctx, recipe)
    ctx.result = process(ctx.canonical, ctx.options)
    ctx.result_key = result_key(ctx, recipe)
    return ctx.result


def summarize(ctx: RunContext) -> dict[str, Any]:
    result = ctx.result
    canonical = ctx.canonical
    if result is None or canonical is None:
        return {}
    return {
        "rows_emitted": len(canonical.rows),
        "rows_dropped": len(canonical.dropped),
        "findings_by_code": result.counts_by_code(),
        "errors": len(result.open_errors()),
        "ack_required": len(result.unacknowledged(ctx.options.acknowledged)),
        "publishable": result.publishable,
    }


def make_pipeline_tools(ctx: RunContext) -> list[BaseTool]:
    @tool
    def run_pipeline() -> str:
        """Run the current candidate recipe and the Affiliate rules. Returns counts and a finding summary."""
        if ctx.candidate_recipe is None:
            return fail("no recipe yet: call write_standard_recipe or register_authored_recipe first")
        try:
            build(ctx, ctx.candidate_recipe)
        except RecipeFailed as exc:
            return fail(f"recipe failed: {exc}")
        return ok(**summarize(ctx))

    return [run_pipeline]
